### ISSUE TITLE
Replace date_default_timezone_set

### ISSUE THREAD

**Issue by JosVelasco** [MSBtheDestroyer/WordPress-Performance-Diagnostic-Tool#3]
This is easy to identify. After activating the plugin, it shows, at least in my WordPress, this critical issue:

PHP default timezone was changed after WordPress loading by a date_default_timezone_set() function call. This interferes with correct calculations of dates and times.

I guess you need that to generate the report, but it appears to affect the whole WordPress install.

**Comment by MSBtheDestroyer** [comment]
I would have never seen this due to my location being the same as the server. Thank you! I am now looking up the server timezone, and setting it that way. Let me know if there are any issues
